srid/haskell-flake

.gitignore, flake-module.nix, flake.nix
Copies `haskell.nix` from https://github.com/srid/haskell-template/pull/22 and exposes it via the flake.
=> Add code from haskell-template

flake-module.nix
=> `pkgs.lib.getExe` is required to `nix run` a Cabal drv

README.md, flake-module.nix
Resolves #10 
In lieu of this magic, we now allow arbitrary keys in projects attr set ... which keys are automatically propagated to `packages`, `apps` and `devShells`. This way the user can name their (only) project to be `default` and don't have to set them manually as defaults.
=> Remove automatic injection of `default` attrs

README.md, flake-module.nix
=> Make `buildTools` respect overrides

flake-module.nix
Closes #19
- Add `hlintCheck.enable` option (false by default); adds a flake check to run hlint
- Rename `enableHLSCheck` to `hlsCheck.enable` for consistency
- Internal: dev shell check no longer redirect to `$out` (instead, it simply touches it).
=> Add a check for `hlint`; rename the HLS check option

flake-module.nix
As one small step toward #7 
Also makes `name` optional mandatory because we need it to create the final package set. It will be implicitly necessary as part of #7 anyway.
=> Replace `envFunc` with `shellFor`; make `name` mandatory

README.md, flake-module.nix
Resolves #7 and resolves #2
~~**Not ready to be merged due to infinite recursion error**~~ Fixed
=> Multi-package projects

flake-module.nix
This catches incomplete release tarballs before they get out.
Closes #35 
It's unconditional and unconfigurable to keep it simple. Can adapt when there's a need.
=> Use `buildFromCabalSdist` on local packages

CHANGELOG.md, example/flake.nix, flake-module.nix, runtest.sh, test/flake.nix
Resolves #37 (to be squash merged)
- Group `buildTools` (renamed to `tools`), `hlsCheck` and `hlintCheck` under the `devShell` submodule option
- Allow disabling them all using `devShell.enable = false;` (useful if you want haskell-flake to produce _just_ the package outputs).
cc @Kranzes
=> Add `devShell` submodule; allow disabling dev environment

README.md
Git will show the last line as changed every time a change is made to `README.md`, with the following message : `\ No newline at end of file`
The alternative for this will be to use `git add -p` to choose which hunk gets staged, but that could add up some manual work.
This problem could be specific to unix/linux (not sure)
=> README.md: added a \n at the end of file

flake-module.nix, haskell-project.nix
@roberth What do you think? The entirety of `haskell-project.nix` continues to remain responsible for creating the `config` implementation for `haskellProjects.foo`
=> Keep all project config in haskell-project.nix

CHANGELOG.md, docs.sh, flake-module.nix, haskell-project.nix, runtest.sh
#52
Access to `finalPackages` was useful for some troubleshooting.
This also adds the docs to CI and adds a script to preview the docs locally.
=> Expose `finalPackages`

haskell-project.nix
After moving code around, I think I accidentally duplicated the implementation of finalPackages, which has lead to the problem:
> It looks like `readonly` has no effect, because I can still set `finalPackages.foo = ./.;` (even `finalPackages = ./.;`) in `test/flake.nix`?
With this fix, it reports:
error: The option `perSystem.x86_64-linux.haskellProjects.default.finalPackages' is read-only, but it's set multiple times. Definition values:
- In `/nix/store/n0vj61wy18j094y6gpzjvq5g0w63d637-source/flake.nix, via option perSystem'
- In `/nix/store/yp9drmdqfgq74c5ap90cq9jqis4yiw41-source/haskell-project.nix'
I suspect that it happened when I did a
git checkout <rev> haskell-project.nix
at some point, with the goal of easily minimizing the diff. That was probably inaccurate.
=> Deduplicate `finalPackages`

CHANGELOG.md, flake-module.nix, test/flake.nix
A step towards #12
[^r]: From @roberth on [Matrix](https://matrix.to/#/!gcrYWdPsIUOFpXFDHB:matrix.org/$ZOYhSXRWLJne7vr9Wz0FkZV27eOzrSa9dRP8LALV2mM?via=matrix.org&via=nixos.dev&via=gaze.systems):
> I think what's missing from the picture is a flake attribute for publishing those modules, and setting up the module arguments for those modules so that they don't have to rely on variables from the lexical scope. The lexical scope is too specific to the local project, not including things like the consuming project's pkgs and whatnot [..] oh and for publishing a module, you can use `types.deferredModule`, which is takes modules, turns them into a single module, but does cause them to be evaluated; returning a module syntax instead of an evaluated configuration
=> Make `overrides` an overlay type rather than a `functionTo`

CHANGELOG.md, flake-module.nix
This, incidentally, allows a _mix_ of top-level and sub-cabal files, but that is okay (we will assume that the user knows what they are doing).
Will further expand the logic in #90 to support `package.yaml`.
=> Simplify .cabal files detection

.github/workflows/ci.yaml, README.md, doc/howto.md, doc/howto/dependency.md, doc/index.md, doc/index.yaml
Markdown files that are published to https://haskell.flake.page/
Can potentially be moved to https://github.com/hercules-ci/flake.parts-website/issues/162 one day
=> Add documentation

CHANGELOG.md, doc/guide/modules.md, nix/flake-module.nix, nix/haskell-project.nix
Resolves #84 
The idea here is to expose the local packages and overrides for reuse in downstream flake. Could well build a network of haskell flakes this way.
=> Add a default for `haskellFlakeProjectModules`

CHANGELOG.md, nix/flake-module.nix, nix/haskell-project.nix, test/flake.nix, test/script, test/test.sh
> Extra Haskell libraries available in the shell's environment.
I'm already using a worse implementation of this in hercules-ci-agent to make as `runghc` shebang script work: https://github.com/hercules-ci/hercules-ci-agent/commit/6da8c81312b36e81e0f674780585571998c47d51 (quickly hacked together at release time...)
This is an improved version of that with
- a test
- no clobbering of the `extraDependencies` parameter
I've also validated it locally with hercules-ci-agent.
=> Add `devShell.extraLibraries` option

nix/flake-module.nix
closes #118 
default-project-modules.nix expects withSystem as input but fails with attribute missing and hence has to be explicitly inherited in specialArgs
=> fix: include withSystem as specialArgs

Jenkinsfile
We'll continue to use Github Actions as the primary CI, as Jenkins logs are not publicly exposed. 
Main benefits Jenkins provides is the faster CI feedback; and eventually, M1 macOS support. I'm also exploring Jenkins lately for Nix builds, so this PR is also part of dogfooding my setup https://github.com/srid/nixos-config/pull/34 in a few projects.
=> Add Jenkins CI (secondary CI)

CHANGELOG.md, nix/flake-module.nix
Resolves #62 
(This is required to demonstrate the `inputsFrom` alternative to #133)
=> Add `autoWire` option, to control flake outputs

CHANGELOG.md, nix/flake-module.nix, nix/haskell-project.nix
When the user has `autoWire = false;`, there is currently no way to get the `checks`. This PR fixes that.
Used in https://github.com/srid/haskell-template/pull/99
=> Add `outputs.checks`

CHANGELOG.md, nix/build-haskell-package.nix, nix/flake-module.nix, nix/haskell-project.nix, nix/logging.nix
Also make haskell-flake produce more debug output (if `debug` is enabled by the user)
=> Run `cleanSourceWith` *before* `cabal2nix`

CHANGELOG.md, nix/flake-module.nix, nix/haskell-project.nix
`justStaticExecutables` is problematic because it can produce double builds (see #146), so just use `getBin` which is especially useful if the user does `enableSeparateBinOutputs` on the user sude.
=> exe: Use `getBin` instead of `justStaticExecutables`

CHANGELOG.md, nix/modules/project.nix, nix/modules/project/defaults.nix, nix/modules/project/devshell.nix
See the last point in https://github.com/srid/haskell-flake/issues/101#issuecomment-1528006895 for context
This PR enables users to change the hardcoded value here:
https://github.com/srid/haskell-flake/blob/fb1a3c32a8efd1c7bb4a9fe1f68a42e0114dd533/nix/modules/project/devshell.nix#L86-L92
And then use it (via project `imports`) in multiple projects.
We could as well add a default option for override `settings` (#101) to solve #146 in a better way.
=> Add `defaults` submodule

CHANGELOG.md, nix/modules/project/devshell.nix
The `shellFor` function allows specifying the `doBenchmark` attribute to include the benchmark's `build-depends` from the `.cabal` file in the derivation. We have to expose this option as an attribute in the `devShellSubmodule` of haskell-flake.
As a hack this attribute input can still be passed to `shellFor` like, `devShell.mkShellArgs.doBenchmark = true;` but that's not the intended behaviour of `mkShellArgs` option.
In addition to the above change, this PR also makes `withHoogle` input to `shellFor` also a configurable option under `devShellSubmodule`.
=> `benchmark` and `hoogle` option in devShellSubmodule

README.md
I felt that that the Readme was not conveying how convenient this project is for Haskell development in Nix so i extended it.
@srid Feel free to edit, request changes or delete this PR.
And thanks for this great tool.
=> Extend README.md to focus on the benefits

nix/modules/project/devshell.nix
`extraDependencies` was added as an argument to `shellFor` only after: https://github.com/NixOS/nixpkgs/commit/2e87d165f74411ae00f964a508945696969ff53d
=> `devShell.extraLibraries`: abort when using an older commit of nixpkgs

CHANGELOG.md, nix/build-haskell-package.nix
Closes #220 
`buildFromCabalSdist` has problems; see #220 
So we are switching to the slightly less performant `buildFromSdist`.
=> Switch to `buildFromSdist`

CHANGELOG.md, nix/modules/project/defaults.nix, nix/modules/project/devshell.nix
Otherwise, eager evaluation will always evaluate the defaults.
=> Make `devShell.tools` a lazyAttrsOf

dev/flake.nix, flake.nix
`../.` cannot be accessed in impure mode.
=> dev: treefmt: specify projectRoot from flake input

.github/workflows/ci.yaml, doc/test.sh, flake.nix, runtest.sh, test/common.sh, test/flake.nix
Resolves #239
The flake check builds on Darwin, but not Linux. See https://github.com/srid/haskell-flake/issues/241
=> Run tests as a flake check; macOS CI for tests

CHANGELOG.md, nix/modules/project-tests.nix, nix/modules/project/default.nix, nix/modules/project/devshell.nix, nix/modules/project/outputs.nix, nix/modules/project/settings/all.nix, nix/modules/projects.nix
This means we don't support `mkIf` in the exact places where the type was `attrsOf`. Almost always, `mkIf` can be replaced by `optionalAttrs`.
The benefit is that the code becomes much lazier, improving performance and
- Fixes https://github.com/srid/haskell-flake/issues/270
=> attrsOf -> lazyAttrsOf

CHANGELOG.md, flake.nix, nix/modules/project/default.nix, nix/modules/project/outputs.nix, test/otherOverlays/flake.nix, test/otherOverlays/haskell-flake-test.cabal, test/otherOverlays/src/Main.hs
#273 
@roberth Could you try this out?
=> Add `otherOverlays` option

nix/modules/project/settings/all.nix, nix/modules/project/settings/lib.nix
The use of `id` causes the (unused, in effect, ultimately) argument to be eagerly evaluated triggering #283.
This PR allow the use of `null` in the `impl` option, thus it resolves #283.
=> Unused `settings.<name>.impl`: use `null` instead of `id`

doc/settings.md, nix/modules/project/settings/default.nix
`buildFromSdist` is fucked up for yet another reason. It breaks `removeReferencesTo`:
https://github.com/srid/haskell-flake/blob/4aab279d0cdd25c9bb3a31ca934c98f2d2a2533d/nix/modules/project/settings/all.nix#L340-L347
The solution here is to apply `removeReferencesTo` *after* `buildFromSdist`.
=> buildFromSdist: deal with breakage of `removeReferencesTo`

CHANGELOG.md, nix/modules/project/defaults.nix
https://github.com/srid/haskell-flake/pull/291#issuecomment-2033350702
Resolves #292
=> buildFromSdist: enable only for local packages

CHANGELOG.md, flake.nix, nix/modules/project-tests.nix, nix/modules/project/defaults.nix, nix/modules/project/settings/default.nix, test/settings-defaults/flake.nix, test/settings-defaults/haskell-flake-test.cabal, test/settings-defaults/src/Main.hs
resolves #261 
`defaults.settings.default-{current, defined, all}` replaces `defaults.settings.default`
TODO:
=> Add granular settings defaults (`defaults.settings.{local, defined, all}`)

CHANGELOG.md, nix/modules/project/defaults.nix
See https://github.com/srid/haskell-flake/pull/298#issuecomment-2068516088
=> Fix: use `buildFromSdist` for packages managed by haskell-flake only

nix/haskell-parsers/default.nix, nix/modules/project/outputs.nix
... instead of failing with inaccurate message (fixed in 462f004 and this PR).
Resolves #213
=> Fix: return empty packages if cabal.project detector did not find any

nix/modules/project/settings/default.nix
lib.attrsets.removeAttrs is only available in newer nixpkgs
This is needed for https://github.com/nammayatri/nammayatri
=> fix: support older nixpkgs

doc/guide.md, doc/hls.md
A start to https://github.com/srid/haskell-flake/issues/245
Preview:
```sh
nix run "github:shivaraj-bh/haskell-flake/hls-guide?dir=doc"
```
=> docs(hls): init HLS doc; document how to disable HLS

.github/workflows/ci.yaml
Drop `aarch64-linux`.
---
And pass access-token to prevent github rate limits. This requires adding,
```yaml
permissions:
contents: read
```
and passing the following argument to `nixci:
```sh
--extra-access-tokens "github.com=${{ secrets.GITHUB_TOKEN }}"
```
=> chore(ci): Add `x86_64-*`

README.md
This a very, very tiny pull request, that adds a comment to the flake template presented in the README.md file.
It has a missing semicolon, which has to be added by readers who copy-paste it, which is a bit annoying.
=> Add missing semicolon to README.md

CHANGELOG.md, example/example.cabal, nix/modules/project/outputs.nix, nix/types/app-type.nix
Supporting https://github.com/hercules-ci/flake-parts/pull/240
Tested with https://github.com/juspay/omnix/pull/251
Running https://omnix.page/om/show.html ..
on Emanote:
on Nammayatri
=> Add `meta.description` to flake apps

CHANGELOG.md, doc/settings.md, nix/modules/project/settings/all.nix, test/simple/flake.nix
Generating this report is just:
```nix
{
settings.<package-name>.stan = true;
}
```
=> Add `stan` setting to output static analysis report

CHANGELOG.md, nix/build-haskell-package.nix, nix/modules/project/packages/package.nix, nix/modules/project/settings/all.nix
Settings such as `settings.<package>.cabalFlags` happen after `cabal2nix` which can be too late when the dependencies depend on a flag.
The option `packages.<package>.cabalFlags` can safely be used instead of `settings.<package>.cabalFlags` in most situations.
Additionally the option `packages.<package>.extraCabal2nixOptions` provides a direct access the options given to cabal2nix.
=> Add `extraCabal2nixOptions` and `cabalFlags` to `packages.<package>`

test/simple/flake.nix, test/simple/haskell-flake-test.cabal
Adds one of the tests mentioned in the description of https://github.com/srid/haskell-flake/issues/262
The existing jailbreak test `foo.jailbreak = true;` doesn't test the expected behaviour because `foo`'s `cabal` file has no dependencies requiring jailbreak
=> buildFromSdist: Test if user can override the `jailbreak` setting
