srid/haskell-flake

flake-module.nix

Use `lazyAttrsOf` to make `overrides` work

---

flake-module.nix

Resolves #18 
@roberth This is the initial implementation; feel free to critique the diff or the design. :-) I'm pretty sure a few things can be improved.

Add HLS `check`

---

flake-module.nix

Fix regression in needing hlintCheck/hlsCheck; and checks not finding build inputs

---

flake-module.nix

To make the diff in #27 and the like palatable.

Refactor to avoid nested-indented submodules

---

flake-module.nix

Unfuck after #32
God, we really need #25

Fix a regression with hlintCheck option scope

---

flake-module.nix

Bug fixes on top of #34
(Yea, we really need #25 )

Fix regression with `checks`

---

flake-module.nix

To make https://github.com/EmaApps/ema/pull/142 work

Fix overlay order

---

.github/workflows/ci.yaml
README.md
example/example.cabal
example/flake.nix
example/src/Main.hs
flake.lock
flake.nix

I did this mostly to address https://github.com/srid/haskell-flake/pull/53#issuecomment-1371606101 (in vain), but I figured it is useful to have on its own as well.
Also adds Github Actions to test the template, which could be considered as first step towards #25

Add flake template & test in Github Actions

---

CHANGELOG.md
README.md
example/flake.nix
flake-module.nix
haskell-project.nix
test/flake.nix

Remove `hlintCheck` in favour of treefmt-nix

---

CHANGELOG.md
flake-module.nix
haskell-project.nix

https://github.com/srid/haskell-flake/issues/52#issuecomment-1371583666

Rename `haskellPackages` -> `basePackages`

---

CHANGELOG.md
example/flake.nix
flake-module.nix
runtest.sh
test/flake.nix

Have `packages` option auto-detect single-package projects

---

.github/workflows/ci.yaml

CI: templates should use pinned nixpkgs

---

haskell-project.nix

Support `hpack`

---

CHANGELOG.md
flake-module.nix
haskell-project.nix
test/flake.nix
test/test.sh

Resolves #83
Details: https://github.com/srid/haskell-flake/pull/83#issuecomment-1433427743
(We need `shellHook` for generating .cabal from package.yaml, so HLS will work.)

Add `devShell.mkShellArgs`

---

CHANGELOG.md
nix/flake-module.nix
nix/haskell-project.nix

Resolves #74
Also a step towards #62

Revamp 'outputs'

---

nix/default-project-modules.nix
nix/flake-module.nix

resolves #108 
IIUC this is the more idiomatic way to do this; let me know if I'm wrong!

Retain default project modules regardless of user configuration

---

nix/haskell-project.nix

Merges to #114 
This restores hpack support such that it https://github.com/nammayatri/nammayatri/pull/109 continues to work (PR #114 in its current form broke it[^1]). We probably should add another test case for a project with `package.yaml` only (no .cabal).
[^1]: See:
```
> source root is beckn-spec-0.1.0.0
> setting SOURCE_DATE_EPOCH to timestamp 1000000000 of file beckn-spec-0.1.0.0/src/Beckn/Types/Core/Taxi/Track/Order.hs
> patching sources
> package.yaml: Yaml file not found: /private/tmp/nix-build-beckn-spec-0.1.0.0.drv-0/beckn-spec-0.1.0.0/package.yaml
> /nix/store/559pz0w6zlvw8yyxah9s10fhaz400vaj-stdenv-darwin/setup: line 138: pop_var_context: head of shell_variables not a function context
For full logs, run 'nix log /nix/store/7gxn8hmgxvzwic3gm6g5x7b74bcpw36b-beckn-spec-0.1.0.0 …
```

Restore original hpack generation logic

---

example/test.sh
nix/find-haskell-paths/test.sh
runtest.sh
test/common.sh
test/hpack/flake.nix
test/hpack/package.yaml
test/hpack/script
test/hpack/src/Main.hs
test/hpack/test.sh
test/simple/flake.nix
test/simple/test.sh
test/with-subdir/flake.nix
test/with-subdir/test.sh

And refactor so that nixpkgs/flake-parts pinning happens in one place.
#117

Add test for `hpack` support

---

runtest.sh
test/README.md
test/project-module/flake.nix
test/project-module/haskell-flake-test.cabal
test/project-module/src/Main.hs
test/project-module/test.sh

Add test for verifying default project modules

---

CHANGELOG.md
nix/flake-module.nix

Resolves #142 
(Not removing existing options in this PR)

Change `autoWire` to be an enum type

---

test/with-subdir/test.sh

We expect the CI to fail due to #145

Add a test to check that cabal2nix does not unnecessarily re-evaluate

---

nix/modules/project-modules.nix
nix/modules/project.nix
nix/modules/project/outputs.nix
nix/modules/project/package.nix
nix/modules/project/packages.nix
nix/modules/project/settings/check.nix
nix/modules/project/settings/custom.nix
nix/modules/project/settings/default.nix
nix/modules/project/settings/executableProfiling.nix
nix/modules/project/settings/extraBuildDepends.nix
nix/modules/project/settings/haddock.nix
nix/modules/project/settings/justStaticExecutables.nix
nix/modules/project/settings/lib.nix
nix/modules/project/settings/libraryProfiling.nix
nix/modules/project/settings/removeReferencesTo.nix
test/project-module/flake.nix

This represents (1) and (2) of https://github.com/srid/emanote/pull/437#discussion_r1198033950

Split `packages` and `settings`

---

CHANGELOG.md
nix/modules/project/settings/all.nix
test/simple/flake.nix

Fixes #177. I didn't do much testing but this change seems to solve my immediate issue.

Fix `settings.<name>.cabalFlags` implementation

---

CHANGELOG.md
nix/modules/project/packages/package.nix
nix/modules/project/settings/all.nix

https://github.com/NixOS/nixpkgs/pull/247937/files 
types.string raise error or give warnings

replace types.string with types.str

---

dev/flake.lock
dev/flake.nix

Something's messed up with the treefmt-check,
https://github.com/srid/haskell-flake/actions/runs/7885297185/job/21517994837

dev: Update flake inputs

---

dev/flake.nix

Debugging gh self-runner failure ...

dev: Disable treefmt check

---

flake.nix
test/common.sh
test/flake.nix
test/simple/flake.nix

In preparation to add new tests.
Eventually, we want to automate this in CI, proxying via example/flake.lock (#249)

test: Update nixpkgs

---

test/simple/flake.nix

Reproduce #238
Fix upcoming in https://github.com/srid/haskell-flake/pull/253

Reproduce #238

---

example/flake.lock
flake.nix
test/common.sh
test/flake.nix

tests: Derive nixpkgs/flake-parts rev from`example/flake.lock`

---

.github/workflows/ci.yaml
flake.nix

Testing https://github.com/srid/nixci/pull/50

ci: Use nixci's github actions matrix generator

---

doc/examples.md

Hello `haskell-flake` contributors! I've been using `haskell-flake` for over a year now and have had nothing but positive experiences
I have an open source Haskell project which is getting ready to be released on Hackage and it has a nice `Nix`+`GitHub Action` CI. I would be happy to share it as an example of CI with build, tests, development environment and documentation generation for Haskell project based on `haskell-flake`

Add KovalevDima/ClickHaskell project example

---

flake.nix

https://omnix.page/om/init.html#spec

nix: Add `om init` template params

---

example/flake.lock

Reverts srid/haskell-flake#372

Revert "Update example/flake.lock"

---

CHANGELOG.md
nix/modules/project/settings/all.nix

Should've been part of https://github.com/srid/haskell-flake/pull/419

Add `previousIntermediates` setting
